server:
  port: 8080
  servlet:
    context-path: "/"


spring:
  # https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_default}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${MYSQL_USERNAME:mysql}"
    password: "${MYSQL_PASSWORD:root}"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      generate-ddl: true
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  flyway:
    enabled: true
#    locations: classpath:db/migration/*.sql
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_default}"
    user: "${MYSQL_USERNAME:mysql}"
    password: "${MYSQL_PASSWORD:root}"

#logging:
#  level:
#    web: debug
#    root: debug