server:
  port: 8080
  servlet:
    context-path: "/api"



spring:
  # https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_default}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${MYSQL_USERNAME:mysql}"
    password: "${MYSQL_PASSWORD:root}"
    hikari:
      password: "${MYSQL_PASSWORD:root}"
      username: "${MYSQL_USERNAME:mysql}"
      jdbc-url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_default}"
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      generate-ddl: false
    properties:
      show-sql: false
      hibernate:
        format_sql: false
        show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  flyway:
    enabled: true
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_default}"
    user: "${MYSQL_USERNAME:mysql}"
    password: "${MYSQL_PASSWORD:root}"

logging:
  level:
    web: debug
    root: debug